import { CONNECTION_STATUS, LIFECYCLE_STATES } from '../constants/connectionStatus';

export const getLifecycleState = (status) => {
  if (!status || status === CONNECTION_STATUS.NOT_APPLIED) {
    return LIFECYCLE_STATES.REGISTERED;
  }

  // Exact matches
  const reverseMap = {
    [CONNECTION_STATUS.PENDING]: LIFECYCLE_STATES.PENDING,
    [CONNECTION_STATUS.UNDER_REVIEW]: LIFECYCLE_STATES.UNDER_REVIEW,
    [CONNECTION_STATUS.APPROVED]: LIFECYCLE_STATES.APPROVED,
    [CONNECTION_STATUS.ENGINEER_ASSIGNED]: LIFECYCLE_STATES.ENGINEER_ASSIGNED,
    [CONNECTION_STATUS.VISIT_SCHEDULED]: LIFECYCLE_STATES.VISIT_SCHEDULED,
    [CONNECTION_STATUS.INSPECTION_COMPLETED]: LIFECYCLE_STATES.INSPECTION_COMPLETED,
    [CONNECTION_STATUS.INSTALLATION_IN_PROGRESS]: LIFECYCLE_STATES.INSTALLATION_IN_PROGRESS,
    [CONNECTION_STATUS.METER_INSTALLED]: LIFECYCLE_STATES.METER_INSTALLED,
    [CONNECTION_STATUS.CONNECTION_ACTIVATED]: LIFECYCLE_STATES.CONNECTION_ACTIVATED,
    [CONNECTION_STATUS.COMPLETED]: LIFECYCLE_STATES.COMPLETED,
    [CONNECTION_STATUS.REJECTED]: LIFECYCLE_STATES.REJECTED,
    [CONNECTION_STATUS.WITHDRAWN]: LIFECYCLE_STATES.WITHDRAWN
  };

  return reverseMap[status] || LIFECYCLE_STATES.REGISTERED;
};
